title: EEN Fish Farms

keywords: >- # website keywords
  catfish, fish farms, eenfishfarms, website, consulting, pond, fingerlings, acquaculture, farm 

description: >- # This means ignore newlines until "baseurl;"
  The official website for EEN Fish Farms

baseurl: "" #
url: "" #


plugins:
  - jekyll-feed
