title: eenfishfarms

keywords: >- # website keywords
  catfish, fish farms, eenfishfarms, website, consulting, pond, fingerlings, acquaculture, farm 

description: >- # This means ignore newlines until "baseurl;"
  The official website for eenfishfarms

baseurl: "" #
url: "" #


plugins:
  - jekyll-feed