title: een fish farm

keywords: >- # website keywords
  catfish, fish farm, eenfishfarm, website, consulting, pond, fingerlings, acquaculture, farm 

description: >- # This means ignore newlines until "baseurl;"
  This is the the official website for een fish farm

baseurl: "" #
url: "" #


plugins:
  - jekyll-feed